# Generated by Django 5.2.7 on 2025-10-02 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('title', models.CharField(max_length=50, verbose_name='菜单标题')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单图标')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=200, null=True, verbose_name='组件路径')),
                ('redirect', models.CharField(blank=True, max_length=200, null=True, verbose_name='重定向路径')),
                ('menu_type', models.IntegerField(choices=[(1, '目录'), (2, '菜单'), (3, '按钮')], default=2, verbose_name='菜单类型')),
                ('permission_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限标识')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('is_keep_alive', models.BooleanField(default=True, verbose_name='是否缓存')),
                ('is_affix', models.BooleanField(default=False, verbose_name='是否固定标签')),
                ('is_frame', models.BooleanField(default=False, verbose_name='是否外链')),
                ('frame_src', models.CharField(blank=True, max_length=500, null=True, verbose_name='外链地址')),
                ('visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单管理',
                'db_table': 'rbac_menu',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分配时间')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.menu', verbose_name='菜单')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色菜单',
                'verbose_name_plural': '角色菜单管理',
                'db_table': 'rbac_role_menu',
                'unique_together': {('role', 'menu')},
            },
        ),
    ]
