# Generated by Django 4.2.25 on 2025-10-03 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_menu_rolemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='API名称')),
                ('path', models.CharField(max_length=500, verbose_name='API路径')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], max_length=10, verbose_name='请求方法')),
                ('description', models.TextField(blank=True, verbose_name='API描述')),
                ('require_auth', models.BooleanField(default=True, verbose_name='需要认证')),
                ('require_permission', models.BooleanField(default=True, verbose_name='需要权限')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API管理',
                'verbose_name_plural': 'API管理',
                'db_table': 'rbac_api',
                'ordering': ['group__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApiGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('description', models.TextField(blank=True, verbose_name='分组描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API分组',
                'verbose_name_plural': 'API分组',
                'db_table': 'rbac_api_group',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='请求数据')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='响应数据')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('response_time', models.FloatField(verbose_name='响应时间(ms)')),
                ('log_type', models.CharField(choices=[('request', '请求'), ('response', '响应'), ('error', '错误')], default='request', max_length=20, verbose_name='日志类型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.api', verbose_name='API')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'API访问日志',
                'verbose_name_plural': 'API访问日志',
                'db_table': 'rbac_api_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='api',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.apigroup', verbose_name='API分组'),
        ),
        migrations.AlterUniqueTogether(
            name='api',
            unique_together={('path', 'method')},
        ),
    ]
