# Generated by Django 4.2.25 on 2025-10-03 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_api_apigroup_apilog_api_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'ordering': ['group', 'path'], 'verbose_name': 'API', 'verbose_name_plural': 'API管理'},
        ),
        migrations.AlterModelOptions(
            name='apigroup',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': 'API分组', 'verbose_name_plural': 'API分组管理'},
        ),
        migrations.AlterModelOptions(
            name='apilog',
            options={'ordering': ['-created_at'], 'verbose_name': 'API日志', 'verbose_name_plural': 'API日志管理'},
        ),
        migrations.AlterModelOptions(
            name='policyrule',
            options={'ordering': ['role_id', 'path'], 'verbose_name': '权限策略规则', 'verbose_name_plural': '权限策略规则管理'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': '用户', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterUniqueTogether(
            name='policyrule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='api',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='api',
            name='require_auth',
        ),
        migrations.RemoveField(
            model_name='api',
            name='require_permission',
        ),
        migrations.RemoveField(
            model_name='api',
            name='status',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='log_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='custom_data_scope',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='api',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AddField(
            model_name='policyrule',
            name='path',
            field=models.CharField(default='', max_length=200, verbose_name='路径'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_scope',
            field=models.IntegerField(choices=[(1, '全部数据'), (2, '本部门及以下数据'), (3, '本部门数据'), (4, '本人数据')], default=4, verbose_name='数据权限'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='api',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='API描述'),
        ),
        migrations.AlterField(
            model_name='api',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='rbac.apigroup', verbose_name='所属分组'),
        ),
        migrations.AlterField(
            model_name='api',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=10, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=100, verbose_name='API名称'),
        ),
        migrations.AlterField(
            model_name='api',
            name='path',
            field=models.CharField(max_length=200, verbose_name='API路径'),
        ),
        migrations.AlterField(
            model_name='apigroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='分组描述'),
        ),
        migrations.AlterField(
            model_name='apigroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='path',
            field=models.CharField(max_length=200, verbose_name='请求路径'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='request_data',
            field=models.TextField(blank=True, null=True, verbose_name='请求数据'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='response_data',
            field=models.TextField(blank=True, null=True, verbose_name='响应数据'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='response_time',
            field=models.FloatField(verbose_name='响应时间(秒)'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='用户代理'),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='method',
            field=models.CharField(max_length=10, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='policyrule',
            name='role_id',
            field=models.CharField(max_length=50, verbose_name='角色ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AlterUniqueTogether(
            name='policyrule',
            unique_together={('role_id', 'path', 'method')},
        ),
        migrations.AlterModelTable(
            name='user',
            table='rbac_user',
        ),
        migrations.RemoveField(
            model_name='policyrule',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='policyrule',
            name='url_pattern',
        ),
    ]
