# Generated by Django 4.2.25 on 2025-10-03 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开数据')),
                ('data_level', models.IntegerField(choices=[(1, '公开数据'), (2, '部门数据'), (3, '私有数据'), (4, '机密数据')], default=2, verbose_name='数据级别')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('review', '待审核'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章管理',
                'db_table': 'demo_article',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开数据')),
                ('data_level', models.IntegerField(choices=[(1, '公开数据'), (2, '部门数据'), (3, '私有数据'), (4, '机密数据')], default=2, verbose_name='数据级别')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=20, verbose_name='文件类型')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('summary', models.TextField(blank=True, verbose_name='文档摘要')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档管理',
                'db_table': 'demo_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开数据')),
                ('data_level', models.IntegerField(choices=[(1, '公开数据'), (2, '部门数据'), (3, '私有数据'), (4, '机密数据')], default=2, verbose_name='数据级别')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='预算')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('in_progress', '进行中'), ('testing', '测试中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planning', max_length=20, verbose_name='项目状态')),
                ('priority', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '紧急')], default=2, verbose_name='优先级')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目管理',
                'db_table': 'demo_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开数据')),
                ('data_level', models.IntegerField(choices=[(1, '公开数据'), (2, '部门数据'), (3, '私有数据'), (4, '机密数据')], default=2, verbose_name='数据级别')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('status', models.CharField(choices=[('todo', '待办'), ('in_progress', '进行中'), ('review', '待审核'), ('completed', '已完成'), ('cancelled', '已取消')], default='todo', max_length=20, verbose_name='任务状态')),
                ('priority', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '紧急')], default=2, verbose_name='优先级')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='预估工时')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='实际工时')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务管理',
                'db_table': 'demo_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
